DROP PROCEDURE Login_SP;

DROP VIEW V_LoginAttempts;
DROP VIEW V_Sessions;

DROP TABLE Accounts CASCADE CONSTRAINTS;
DROP TABLE LoginAttempts CASCADE CONSTRAINTS;
DROP TABLE Sessions CASCADE CONSTRAINTS;

DROP SEQUENCE Accounts_ID_SEQ;