DROP PROCEDURE Login_SP;
DROP PROCEDURE Unlock_SP;
DROP PROCEDURE CreateAccount_SP;

DROP TABLE LockEvents CASCADE CONSTRAINTS;
DROP TABLE EventReasons CASCADE CONSTRAINTS;
DROP TABLE Sessions CASCADE CONSTRAINTS;
DROP TABLE LoginAttempts CASCADE CONSTRAINTS;
DROP TABLE Accounts CASCADE CONSTRAINTS;
DROP TABLE AccountTypes CASCADE CONSTRAINTS;

DROP SEQUENCE Accounts_ID_SEQ;
DROP SEQUENCE AccountTypes_ID_SEQ;
DROP SEQUENCE LockEvents_ID_SEQ;
DROP SEQUENCE EventReasons_ID_SEQ;